drawsee:
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 42.193.107.127
    port: 3246
    username: root
    password: cyf829CMT917
  minio:
    endpoint: http://42.193.107.127:9046
    accessKey: XOKQYoPekwnGasqY9cB3
    secretKey: Z65Sy7T2pegQFj5A7ZnRzCFeJdTBV2O4qj5GQkH3
    bucketName: drawsee
  models:
    doubao:
      base_url: "https://ark.cn-beijing.volces.com/api/v3"
      api_key: "38e2b6ed-2af3-440d-a28b-2f3b1c4aaafc"
      model_name: "ep-20250129233540-8rztb"
    deepseekV3:
      base_url: "https://ark.cn-beijing.volces.com/api/v3"
      api_key: "38e2b6ed-2af3-440d-a28b-2f3b1c4aaafc"
      model_name: "ep-20250320211327-hgz94"
    doubaoVision:
      base_url: "https://ark.cn-beijing.volces.com/api/v3"
      api_key: "38e2b6ed-2af3-440d-a28b-2f3b1c4aaafc"
      model_name: "ep-20250323134257-7l4fn"